# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(verbose_name='create date')),
            ],
        ),
        migrations.CreateModel(
            name='InputOutputPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IOSignalsDeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_O', models.CharField(choices=[('I', 'Input'), ('O', 'Output')], max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(verbose_name='create date')),
            ],
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SignalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(verbose_name='create date')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.SignalType'),
        ),
        migrations.AddField(
            model_name='signal',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.SignalUnit'),
        ),
        migrations.AddField(
            model_name='iosignalsdevicetype',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Signal'),
        ),
        migrations.AddField(
            model_name='inputoutputport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.MonitoringDevice'),
        ),
        migrations.AddField(
            model_name='inputoutputport',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Signal'),
        ),
    ]
