# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringdevice',
            name='descr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='ip_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='mac_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='serial',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
