# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20170406_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutputport',
            name='port_label',
            field=models.CharField(default='COM1', help_text='This field must be included in the mqtt topic', max_length=10),
        ),
    ]
