# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_inputoutputport_port_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringdevice',
            name='mac_address',
            field=models.CharField(max_length=40),
        ),
    ]
