# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20170406_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('descr', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
