# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_measuredentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutputport',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.MeasuredEntity'),
        ),
    ]
