# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_inputoutputport_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredentity',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuredentity',
            name='last_updttm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last datetime'),
            preserve_default=False,
        ),
    ]
