# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20170406_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
    ]
