# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_signaltype_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
    ]
