# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_auto_20170406_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringdevice',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
        migrations.AddField(
            model_name='signal',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
        migrations.AlterField(
            model_name='measuredentity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create datetime'),
        ),
        migrations.AlterField(
            model_name='measuredentity',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create date'),
        ),
    ]
