# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20170406_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredentity',
            name='type',
            field=models.CharField(choices=[('M', 'Machine'), ('P', 'Plant')], default='M', max_length=1),
        ),
    ]
