# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_measuredentity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputoutputport',
            old_name='machine',
            new_name='meaured_entity',
        ),
    ]
