# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_auto_20170406_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputoutputport',
            old_name='meaured_entity',
            new_name='measured_entity',
        ),
    ]
