# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_auto_20170406_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputoutputport',
            name='behavior_text',
        ),
    ]
