# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_remove_inputoutputport_behavior_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntityBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descr', models.CharField(max_length=160)),
                ('behavior_text', models.TextField(blank=True, null=True)),
                ('measureEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.MeasuredEntity')),
            ],
        ),
    ]
