# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_measuredentitybehavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupIdleReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=160)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='IdleReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=160)),
                ('classification', models.CharField(choices=[('A', 'Availability'), ('C', 'Capacity'), ('P', 'Performance')], default='A', max_length=1)),
                ('down', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.GroupIdleReason')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuredEntityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=160)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.AddField(
            model_name='measuredentitybehavior',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuredentitybehavior',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
    ]
