# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20170420_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntityHostSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('measured_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.MeasuredEntity')),
            ],
        ),
    ]
