# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_measuredentityhostsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuredentityhostsystem',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='measuredentityhostsystem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='measuredentityhostsystem',
            name='last_updttm',
        ),
        migrations.RemoveField(
            model_name='measuredentityhostsystem',
            name='measured_entity',
        ),
        migrations.AddField(
            model_name='measuredentityhostsystem',
            name='measuredentity_ptr',
            field=models.OneToOneField(auto_created=True, default='9', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.MeasuredEntity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measuredentityhostsystem',
            name='id_compania',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='measuredentityhostsystem',
            name='id_grupo_maquina',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='measuredentityhostsystem',
            name='id_maquina',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='measuredentityhostsystem',
            name='id_planta',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='measuredentityhostsystem',
            name='id_sede',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
