# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_auto_20170421_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineHostSystem',
            fields=[
                ('measuredentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.MeasuredEntity')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
            ],
            bases=('setup.measuredentity',),
        ),
        migrations.CreateModel(
            name='PlantHostSystem',
            fields=[
                ('measuredentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.MeasuredEntity')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
            ],
            bases=('setup.measuredentity',),
        ),
        migrations.RemoveField(
            model_name='measuredentityhostsystem',
            name='measuredentity_ptr',
        ),
        migrations.DeleteModel(
            name='MeasuredEntityHostSystem',
        ),
    ]
