# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0022_auto_20170421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredentity',
            name='descr',
            field=models.CharField(max_length=200),
        ),
    ]
