# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_auto_20170421_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringdevice',
            old_name='type',
            new_name='device_type',
        ),
        migrations.AlterField(
            model_name='inputoutputport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_ports', to='setup.MonitoringDevice'),
        ),
        migrations.AlterField(
            model_name='iosignalsdevicetype',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_signals', to='setup.DeviceType'),
        ),
    ]
