# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_auto_20170428_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlereason',
            name='group',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='inputoutputport',
            name='measured_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_entity', to='setup.MeasuredEntity'),
        ),
        migrations.DeleteModel(
            name='GroupIdleReason',
        ),
    ]
