# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_auto_20170429_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idlereason',
            old_name='group',
            new_name='group_cd',
        ),
    ]
