# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0027_auto_20170429_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=160)),
                ('pixelsWidth', models.IntegerField()),
                ('pixelsHeight', models.IntegerField()),
                ('textColor', models.CharField(choices=[('K', 'Black'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='R', max_length=1)),
                ('backColor', models.CharField(choices=[('K', 'Black'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='K', max_length=1)),
                ('inMode', models.CharField(choices=[('JO', 'Jump out'), ('ML', 'Move Left'), ('MR', 'Move Right'), ('SL', 'Scroll Left'), ('SR', 'Scroll Right')], default='ML', max_length=2)),
                ('outMode', models.CharField(choices=[('JO', 'Jump out'), ('ML', 'Move Left'), ('MR', 'Move Right'), ('SL', 'Scroll Left'), ('SR', 'Scroll Right')], default='ML', max_length=2)),
                ('speed', models.CharField(choices=[('K', 'Black'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], default='2', max_length=1)),
                ('lineSpacing', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('letterSize', models.CharField(choices=[('0', 'Normal 5 (5X5)'), ('1', 'Normal 7 (6X7)'), ('2', 'Normal 14 (8X14)'), ('3', 'Normal 15 (9X15)'), ('4', 'Normal 16 (9X16)'), ('5', 'Normal 11 (9X11)'), ('6', 'Bold 5 (7X5)'), ('7', 'Bold 14 (10X14)'), ('8', 'Bold 15 (10X15)'), ('9', 'Bold 16 (12X16)')], default='1', max_length=1)),
                ('verticalAlignment', models.CharField(choices=[('0', 'Center'), ('1', 'Top'), ('2', 'Bottom')], default=0, max_length=1)),
                ('horizontalAlignment', models.CharField(choices=[('0', 'Center'), ('1', 'Left'), ('2', 'Right')], default=0, max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
    ]
