# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_displaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=160)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=3001, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(65535)])),
            ],
        ),
        migrations.AlterField(
            model_name='displaytype',
            name='pixelsHeight',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='displaytype',
            name='pixelsWidth',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='displaydevice',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.DisplayType'),
        ),
    ]
