# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0029_auto_20170508_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displaytype',
            old_name='backColor',
            new_name='back_color',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='horizontalAlignment',
            new_name='horizontal_alignment',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='inMode',
            new_name='in_mode',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='letterSize',
            new_name='letter_size',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='lineSpacing',
            new_name='line_spacing',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='outMode',
            new_name='out_mode',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='pixelsHeight',
            new_name='pixels_height',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='pixelsWidth',
            new_name='pixels_width',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='textColor',
            new_name='text_color',
        ),
        migrations.RenameField(
            model_name='displaytype',
            old_name='verticalAlignment',
            new_name='vertical_alignment',
        ),
        migrations.AddField(
            model_name='displaydevice',
            name='reference_cd',
            field=models.CharField(default='DISPLAY_01', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='displaydevice',
            name='port',
            field=models.IntegerField(default=3001, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)]),
        ),
    ]
