# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0031_auto_20170517_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredentity',
            name='code',
            field=models.CharField(max_length=180),
        ),
    ]
