# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0033_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='compania',
            new_name='id_compania',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_sede',
            field=models.CharField(default='sede0', max_length=60),
            preserve_default=False,
        ),
    ]
