# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0034_auto_20170528_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_planta',
            field=models.CharField(default=4, max_length=60),
            preserve_default=False,
        ),
    ]
