# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0035_employee_id_planta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntityStateBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_behavior_type', models.CharField(choices=[('AR', 'Activity Registration')], default=0, max_length=1)),
                ('descr', models.CharField(max_length=160)),
                ('behavior_text', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('measure_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_behaviors', to='setup.MeasuredEntity')),
            ],
        ),
    ]
