# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0036_measuredentitystatebehavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredentitystatebehavior',
            name='state_behavior_type',
            field=models.CharField(choices=[('AR', 'Activity Registration')], default=0, max_length=2),
        ),
    ]
