# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0037_auto_20170530_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntityTransitionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_from', models.CharField(choices=[('O', 'Operating'), ('S', 'Schedule Down'), ('U', 'Unchedule Down')], default='S', max_length=1)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.MeasuredEntityStateBehavior')),
                ('measure_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measured_states', to='setup.MeasuredEntity')),
                ('reason_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='setup.IdleReason')),
            ],
        ),
    ]
