# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0039_auto_20170606_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='protocol',
            field=models.CharField(choices=[('Q', 'MQTT'), ('M', 'ModBus')], default='Q', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measuredentitytransitionstate',
            name='state_from',
            field=models.CharField(choices=[('O', 'Operating'), ('S', 'Schedule Down'), ('U', 'Unchedule Down'), ('D', 'Undefined')], default='S', max_length=1),
        ),
    ]
