# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0040_auto_20170611_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleReasonHostSystem',
            fields=[
                ('idlereason_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.IdleReason')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_razon_parada', models.CharField(max_length=60)),
            ],
            bases=('setup.idlereason',),
        ),
    ]
