# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0041_idlereasonhostsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutputport',
            name='port_label',
            field=models.CharField(default='COM1', help_text='This field must be included in the mqtt and modbus topic', max_length=60),
        ),
    ]
