# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0042_auto_20170628_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutputport',
            name='refresh_time_ms',
            field=models.IntegerField(default=5000, help_text='It specifies how often a new measured is obtained in milliseconds'),
        ),
    ]
