# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0043_inputoutputport_refresh_time_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredEntityScheduledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_event_type', models.CharField(choices=[('AG', 'OEE Aggregation')], default=0, max_length=2)),
                ('descr', models.CharField(max_length=160)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('day_time', models.TimeField(verbose_name='day_time')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('measure_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event', to='setup.MeasuredEntity')),
            ],
        ),
        migrations.AddField(
            model_name='idlereason',
            name='cause',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='descripcion_sin_trabajo',
            field=models.CharField(default='sin_trabajo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='factor_conversion_emp_ciclo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='factor_conversion_kg_ciclo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='factor_conversion_mil_ciclo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='tasa_vel_esperada',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinehostsystem',
            name='tiempo_esperado_config',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='displaydevice',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.DisplayType'),
        ),
        migrations.AlterField(
            model_name='inputoutputport',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.Signal'),
        ),
        migrations.AlterField(
            model_name='iosignalsdevicetype',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.Signal'),
        ),
        migrations.AlterField(
            model_name='measuredentitytransitionstate',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.MeasuredEntityStateBehavior'),
        ),
        migrations.AlterField(
            model_name='measuredentitytransitionstate',
            name='reason_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='setup.IdleReason'),
        ),
        migrations.AlterField(
            model_name='monitoringdevice',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.DeviceType'),
        ),
        migrations.AlterField(
            model_name='monitoringdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringdevice',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.SignalType'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.SignalUnit'),
        ),
    ]
