# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0044_auto_20190410_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydevice',
            name='entity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='display_entity', to='setup.MeasuredEntity'),
            preserve_default=False,
        ),
    ]
