# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0045_displaydevice_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreggateMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=160)),
                ('attribute', models.CharField(max_length=160)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(default='1', max_length=1)),
                ('type_child', models.CharField(default='1', max_length=1)),
                ('scale', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='displaydevice',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_entity', to='setup.MeasuredEntity'),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='descripcion_sin_trabajo',
            field=models.CharField(default='sin_trabajo', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='factor_conversion_emp_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='factor_conversion_kg_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='factor_conversion_mil_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='tasa_vel_esperada',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinehostsystem',
            name='tiempo_esperado_config',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreggatemethod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.Period'),
        ),
    ]
