# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-26 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0046_auto_20190423_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=160)),
                ('attribute', models.CharField(max_length=160)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.Period')),
            ],
        ),
        migrations.RemoveField(
            model_name='agreggatemethod',
            name='period',
        ),
        migrations.DeleteModel(
            name='AgreggateMethod',
        ),
    ]
