# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0047_auto_20190426_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='graph_type',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='GraphType',
        ),
    ]
