# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0047_auto_20190426_1424'),
    ]

    operations = [

    ]
