# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0048_auto_20190429_1102'),
    ]

    operations = [
    ]
