# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0049_aggregatemethod_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinehostsystem',
            name='tiempo_refresco',
            field=models.IntegerField(default=5),
        ),
    ]
