# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0051_auto_20190516_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.IntegerField()),
                ('owner_type', models.IntegerField()),
                ('attribute_name', models.CharField(max_length=300)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=300, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measuredattributevalue',
            },
        ),
        migrations.CreateModel(
            name='MeasuringEntityStatusInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.IntegerField()),
                ('owner_type', models.IntegerField()),
                ('datetime_to', models.DateTimeField()),
                ('datetime_from', models.DateTimeField()),
                ('status', models.CharField(max_length=300)),
                ('related_object', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.IntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=300, null=True)),
                ('executed_object_canonical', models.CharField(blank=True, max_length=300, null=True)),
                ('production_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('conversion_1', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('conversion_2', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('actual_production_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('qty_defective', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'measuringentitystatusinterval',
            },
        ),
    ]
