# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0054_auto_20190516_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='graph_type',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='user',
        ),
        migrations.AddField(
            model_name='measuredattributevalue',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 10, 58, 24, 523374)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='GraphType',
        ),
    ]
