# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0055_auto_20190517_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredattributevalue',
            name='value_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
