# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0056_auto_20190517_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measuringentitystatusinterval',
            old_name='conversion_1',
            new_name='conversion1',
        ),
        migrations.RenameField(
            model_name='measuringentitystatusinterval',
            old_name='conversion_2',
            new_name='conversion2',
        ),
    ]
