# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0058_auto_20190517_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperator',
            name='days_interval',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='days_interval',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
