# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0059_auto_20190517_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinehostsystem',
            name='tiempo_refresco',
        ),
        migrations.AddField(
            model_name='measuredentity',
            name='refresh_time',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
