# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0060_auto_20190517_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModBusInputOutputPort',
            fields=[
                ('inputoutputport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.InputOutputPort')),
                ('object_type', models.CharField(choices=[('CO', 'Coil'), ('DI', 'Discrete input'), ('IR', 'Input Register'), ('HR', 'Holding Register')], default='HR', max_length=2)),
                ('access', models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('RW', 'Read Write')], default='R', max_length=2)),
            ],
            bases=('setup.inputoutputport',),
        ),
        migrations.CreateModel(
            name='ModBusMonitoringDevice',
            fields=[
                ('monitoringdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.MonitoringDevice')),
                ('is_concentrator', models.BooleanField(default=False)),
                ('port', models.IntegerField(default=502)),
            ],
            bases=('setup.monitoringdevice',),
        ),
        migrations.CreateModel(
            name='MqttInputOutputPort',
            fields=[
                ('inputoutputport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.InputOutputPort')),
                ('topic_name', models.CharField(max_length=200)),
            ],
            bases=('setup.inputoutputport',),
        ),
        migrations.CreateModel(
            name='MqttMonitoringDevice',
            fields=[
                ('monitoringdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setup.MonitoringDevice')),
                ('port', models.IntegerField(default=502)),
            ],
            bases=('setup.monitoringdevice',),
        ),
    ]
