# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0061_modbusinputoutputport_modbusmonitoringdevice_mqttinputoutputport_mqttmonitoringdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusinputoutputport',
            name='nbr_read',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modbusinputoutputport',
            name='offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modbusinputoutputport',
            name='port',
            field=models.IntegerField(default=502),
        ),
        migrations.AddField(
            model_name='modbusinputoutputport',
            name='unit_id',
            field=models.IntegerField(default=1),
        ),
    ]
