# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('kpi_name', models.CharField(max_length=300)),
                ('api_url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'charts',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('layout', models.CharField(max_length=100)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard'),
        ),
        migrations.AddField(
            model_name='chart',
            name='graph_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='graph_types.GraphType'),
        ),
    ]
