# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='graph_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph_types.GraphType'),
        ),
    ]
