# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190430_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='graph_html_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
