# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-08 14:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_chart_graph_html_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
