# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maquina', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('estado_actual', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
                ('grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.GrupoMaquina')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccionPlaneada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=4)),
                ('mes', models.IntegerField(max_length=2)),
                ('id_produccion', models.CharField(max_length=30)),
                ('id_articulo', models.CharField(max_length=30)),
                ('descr_articulo', models.CharField(max_length=120)),
                ('fechahora_inicial', models.DateTimeField(verbose_name='fecha hora inicio')),
                ('fechahora_final', models.DateTimeField(verbose_name='fecha hora fin')),
                ('num_horas', models.IntegerField(max_length=10)),
                ('cantidad_producir', models.FloatField()),
                ('tasa_esperada', models.FloatField()),
                ('velocidad_esperada', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
                ('grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.GrupoMaquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Maquina')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaPlaneada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=4)),
                ('mes', models.IntegerField(max_length=2)),
                ('fechahora_inicial', models.DateTimeField(verbose_name='fecha hora inicio')),
                ('fechahora_final', models.DateTimeField(verbose_name='fecha hora fin')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
                ('grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.GrupoMaquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Maquina')),
            ],
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, max_length=4, verbose_name='ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=4, max_length=2, verbose_name='mes')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
                ('grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.GrupoMaquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_planta', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
            ],
        ),
        migrations.CreateModel(
            name='RazonParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_razon_parada', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('grupo_razon_parada', models.CharField(max_length=60)),
                ('causa_raiz_parada', models.CharField(max_length=60)),
                ('afecta_capacidad', models.CharField(max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sede', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Compania')),
            ],
        ),
        migrations.AddField(
            model_name='razonparada',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='planta',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta'),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='paradaplaneada',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta'),
        ),
        migrations.AddField(
            model_name='paradaplaneada',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='ordenproduccionplaneada',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta'),
        ),
        migrations.AddField(
            model_name='ordenproduccionplaneada',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
        migrations.AddField(
            model_name='grupomaquina',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Planta'),
        ),
        migrations.AddField(
            model_name='grupomaquina',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonical.Sede'),
        ),
    ]
