# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tipo_actividad', models.CharField(choices=[('S', 'Comienzo Orden de Produccion'), ('E', 'Fin Orden de Produccion'), ('C', 'Comienzo de Parada'), ('F', 'Fin de Parada')], default='S', max_length=1)),
                ('id_razon_parada', models.CharField(max_length=60)),
                ('id_produccion', models.CharField(max_length=30)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'graph_types',
            },
        ),
        migrations.CreateModel(
            name='GrupoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('estado_actual', models.CharField(max_length=2)),
                ('tasa_vel_esperada', models.FloatField(default=0)),
                ('tiempo_esperado_config', models.FloatField(default=0)),
                ('factor_conversion_kg_ciclo', models.FloatField(default=0)),
                ('factor_conversion_mil_ciclo', models.FloatField(default=0)),
                ('factor_conversion_emp_ciclo', models.FloatField(default=0)),
                ('descripcion_sin_trabajo', models.CharField(default='sin_trabajo', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccionPlaneada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('id_produccion', models.CharField(max_length=30)),
                ('id_articulo', models.CharField(max_length=30)),
                ('descr_articulo', models.CharField(max_length=120)),
                ('fechahora_inicial', models.DateTimeField()),
                ('fechahora_final', models.DateTimeField()),
                ('num_horas', models.IntegerField()),
                ('cantidad_producir', models.FloatField()),
                ('tasa_esperada', models.FloatField()),
                ('velocidad_esperada', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaPlaneada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fechahora_inicial', models.DateTimeField(verbose_name='fecha hora inicio')),
                ('fechahora_final', models.DateTimeField(verbose_name='fecha hora fin')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('ano', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=4, verbose_name='mes')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='RazonParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_razon_parada', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('grupo_razon_parada', models.CharField(max_length=60)),
                ('causa_raiz_parada', models.CharField(max_length=60)),
                ('afecta_capacidad', models.CharField(max_length=1)),
                ('clasificacion', models.CharField(default='0', max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('descr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create datetime')),
                ('last_updttm', models.DateTimeField(auto_now=True, verbose_name='last datetime')),
            ],
        ),
    ]
