# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradaplaneada',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paradaplaneada',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
    ]
