# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0004_auto_20170508_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccionplaneada',
            name='fechahora_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordenproduccionplaneada',
            name='fechahora_inicial',
            field=models.DateTimeField(),
        ),
    ]
