# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0005_auto_20170527_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.CharField(max_length=60)),
                ('id_sede', models.CharField(max_length=60)),
                ('id_planta', models.CharField(max_length=60)),
                ('id_grupo_maquina', models.CharField(max_length=60)),
                ('id_maquina', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tipo_actividad', models.CharField(choices=[('S', 'Comienzo Orden de Produccion'), ('E', 'Fin Orden de Produccion'), ('C', 'Comienzo de Parada'), ('F', 'Fin de Parada')], default='S', max_length=1)),
                ('id_razon_parada', models.CharField(max_length=60)),
                ('id_produccion', models.CharField(max_length=30)),
            ],
        ),
    ]
