# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canonical', '0006_activityregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregister',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityregister',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityregister',
            name='last_updttm',
            field=models.DateTimeField(auto_now=True, verbose_name='last datetime'),
        ),
    ]
