# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0007_auto_20170530_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityregister',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
