# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0008_auto_20170530_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproduccion',
            name='mes',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=6, verbose_name='mes'),
        ),
    ]
