# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canonical', '0011_auto_20190423_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='descripcion_sin_trabajo',
            field=models.CharField(default='sin_trabajo', max_length=200),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='factor_conversion_emp_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='factor_conversion_kg_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='factor_conversion_mil_ciclo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tasa_vel_esperada',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tiempo_esperado_config',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='razonparada',
            name='clasificacion',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
